### ISSUE TITLE
Merge

### ISSUE THREAD

**Issue by persianpros** [OpenVisionE2/sh4-apps#2]
Hi my friend,

I just wanted to tell you there is no need to commit what Audioniek commits as I merge with his repo always and if we commit them by hand there will be merge conflicts ;)

Good luck.

**Comment by backup1977** [comment]
Hello

I follow audioniek since he renegot the new cuberevo_micom always has problems, and not stable. I think we better return to the old ipbox/micom if he does not fix that, the old ipbox/micom is very stable.

Regards
